version: '3.1'

services:
  voting:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
        PORT: 8080
        DATABASE_URL: postgres://postgres:psqlpass@postgres:5432/voting
    # volumes:

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: psqlpass
      POSTGRES_USER: postgres
    # ports:
    # volumes: