version: '3.1'

services:
  voting:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      GEL_DSN: gel://gel
      GEL_CLIENT_TLS_SECURITY: insecure

    # volumes:

  gel:
    image: geldata/gel:6.4
    restart: unless-stopped
    environment:
      GEL_SERVER_TLS_CERT_MODE: generate_self_signed
      GEL_SERVER_SECURITY: insecure_dev_mode