version: '3.1'

services:
  voting:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      EDGEDB_DSN: edgedb://edgedb
      EDGEDB_CLIENT_TLS_SECURITY: insecure

    # volumes:

  edgedb:
    image: edgedb/edgedb
    restart: unless-stopped
    environment:
      # EDGEDB_SERVER_PASSWORD: edgedb
      EDGEDB_SERVER_TLS_CERT_MODE: generate_self_signed
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    # ports:
    # volumes:
