/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as JoinRoomIdRouteImport } from './routes/join.$roomId'
import { Route as JShortIdRouteImport } from './routes/j.$shortId'
import { Route as BShortIdRouteImport } from './routes/b.$shortId'
import { Route as RoomRoomIdResultsRouteImport } from './routes/room.$roomId/results'
import { Route as RoomRoomIdBoardRouteImport } from './routes/room.$roomId/board'
import { Route as RoomRoomIdWaitUserIdRouteImport } from './routes/room.$roomId/wait.$userId'
import { Route as RoomRoomIdAdminAdminKeyRouteImport } from './routes/room.$roomId/admin.$adminKey'
import { Route as RoomRoomIdAdminAdminKeyIndexRouteImport } from './routes/room.$roomId/admin.$adminKey/index'
import { Route as RoomRoomIdVoteUserIdVotingKeyRouteImport } from './routes/room.$roomId/vote.$userId.$votingKey'
import { Route as RoomRoomIdAdminAdminKeyWaitingRoomRouteImport } from './routes/room.$roomId/admin.$adminKey/waiting-room'
import { Route as RoomRoomIdAdminAdminKeyQuestionsRouteImport } from './routes/room.$roomId/admin.$adminKey/questions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoomIdRoute = JoinRoomIdRouteImport.update({
  id: '/join/$roomId',
  path: '/join/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const JShortIdRoute = JShortIdRouteImport.update({
  id: '/j/$shortId',
  path: '/j/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const BShortIdRoute = BShortIdRouteImport.update({
  id: '/b/$shortId',
  path: '/b/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdResultsRoute = RoomRoomIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => RoomRoomIdRoute,
} as any)
const RoomRoomIdBoardRoute = RoomRoomIdBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => RoomRoomIdRoute,
} as any)
const RoomRoomIdWaitUserIdRoute = RoomRoomIdWaitUserIdRouteImport.update({
  id: '/wait/$userId',
  path: '/wait/$userId',
  getParentRoute: () => RoomRoomIdRoute,
} as any)
const RoomRoomIdAdminAdminKeyRoute = RoomRoomIdAdminAdminKeyRouteImport.update({
  id: '/admin/$adminKey',
  path: '/admin/$adminKey',
  getParentRoute: () => RoomRoomIdRoute,
} as any)
const RoomRoomIdAdminAdminKeyIndexRoute =
  RoomRoomIdAdminAdminKeyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RoomRoomIdAdminAdminKeyRoute,
  } as any)
const RoomRoomIdVoteUserIdVotingKeyRoute =
  RoomRoomIdVoteUserIdVotingKeyRouteImport.update({
    id: '/vote/$userId/$votingKey',
    path: '/vote/$userId/$votingKey',
    getParentRoute: () => RoomRoomIdRoute,
  } as any)
const RoomRoomIdAdminAdminKeyWaitingRoomRoute =
  RoomRoomIdAdminAdminKeyWaitingRoomRouteImport.update({
    id: '/waiting-room',
    path: '/waiting-room',
    getParentRoute: () => RoomRoomIdAdminAdminKeyRoute,
  } as any)
const RoomRoomIdAdminAdminKeyQuestionsRoute =
  RoomRoomIdAdminAdminKeyQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => RoomRoomIdAdminAdminKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/b/$shortId': typeof BShortIdRoute
  '/j/$shortId': typeof JShortIdRoute
  '/join/$roomId': typeof JoinRoomIdRoute
  '/room/$roomId': typeof RoomRoomIdRouteWithChildren
  '/room/$roomId/board': typeof RoomRoomIdBoardRoute
  '/room/$roomId/results': typeof RoomRoomIdResultsRoute
  '/room/$roomId/admin/$adminKey': typeof RoomRoomIdAdminAdminKeyRouteWithChildren
  '/room/$roomId/wait/$userId': typeof RoomRoomIdWaitUserIdRoute
  '/room/$roomId/admin/$adminKey/questions': typeof RoomRoomIdAdminAdminKeyQuestionsRoute
  '/room/$roomId/admin/$adminKey/waiting-room': typeof RoomRoomIdAdminAdminKeyWaitingRoomRoute
  '/room/$roomId/vote/$userId/$votingKey': typeof RoomRoomIdVoteUserIdVotingKeyRoute
  '/room/$roomId/admin/$adminKey/': typeof RoomRoomIdAdminAdminKeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/b/$shortId': typeof BShortIdRoute
  '/j/$shortId': typeof JShortIdRoute
  '/join/$roomId': typeof JoinRoomIdRoute
  '/room/$roomId': typeof RoomRoomIdRouteWithChildren
  '/room/$roomId/board': typeof RoomRoomIdBoardRoute
  '/room/$roomId/results': typeof RoomRoomIdResultsRoute
  '/room/$roomId/wait/$userId': typeof RoomRoomIdWaitUserIdRoute
  '/room/$roomId/admin/$adminKey/questions': typeof RoomRoomIdAdminAdminKeyQuestionsRoute
  '/room/$roomId/admin/$adminKey/waiting-room': typeof RoomRoomIdAdminAdminKeyWaitingRoomRoute
  '/room/$roomId/vote/$userId/$votingKey': typeof RoomRoomIdVoteUserIdVotingKeyRoute
  '/room/$roomId/admin/$adminKey': typeof RoomRoomIdAdminAdminKeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/b/$shortId': typeof BShortIdRoute
  '/j/$shortId': typeof JShortIdRoute
  '/join/$roomId': typeof JoinRoomIdRoute
  '/room/$roomId': typeof RoomRoomIdRouteWithChildren
  '/room/$roomId/board': typeof RoomRoomIdBoardRoute
  '/room/$roomId/results': typeof RoomRoomIdResultsRoute
  '/room/$roomId/admin/$adminKey': typeof RoomRoomIdAdminAdminKeyRouteWithChildren
  '/room/$roomId/wait/$userId': typeof RoomRoomIdWaitUserIdRoute
  '/room/$roomId/admin/$adminKey/questions': typeof RoomRoomIdAdminAdminKeyQuestionsRoute
  '/room/$roomId/admin/$adminKey/waiting-room': typeof RoomRoomIdAdminAdminKeyWaitingRoomRoute
  '/room/$roomId/vote/$userId/$votingKey': typeof RoomRoomIdVoteUserIdVotingKeyRoute
  '/room/$roomId/admin/$adminKey/': typeof RoomRoomIdAdminAdminKeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/b/$shortId'
    | '/j/$shortId'
    | '/join/$roomId'
    | '/room/$roomId'
    | '/room/$roomId/board'
    | '/room/$roomId/results'
    | '/room/$roomId/admin/$adminKey'
    | '/room/$roomId/wait/$userId'
    | '/room/$roomId/admin/$adminKey/questions'
    | '/room/$roomId/admin/$adminKey/waiting-room'
    | '/room/$roomId/vote/$userId/$votingKey'
    | '/room/$roomId/admin/$adminKey/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/b/$shortId'
    | '/j/$shortId'
    | '/join/$roomId'
    | '/room/$roomId'
    | '/room/$roomId/board'
    | '/room/$roomId/results'
    | '/room/$roomId/wait/$userId'
    | '/room/$roomId/admin/$adminKey/questions'
    | '/room/$roomId/admin/$adminKey/waiting-room'
    | '/room/$roomId/vote/$userId/$votingKey'
    | '/room/$roomId/admin/$adminKey'
  id:
    | '__root__'
    | '/'
    | '/b/$shortId'
    | '/j/$shortId'
    | '/join/$roomId'
    | '/room/$roomId'
    | '/room/$roomId/board'
    | '/room/$roomId/results'
    | '/room/$roomId/admin/$adminKey'
    | '/room/$roomId/wait/$userId'
    | '/room/$roomId/admin/$adminKey/questions'
    | '/room/$roomId/admin/$adminKey/waiting-room'
    | '/room/$roomId/vote/$userId/$votingKey'
    | '/room/$roomId/admin/$adminKey/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BShortIdRoute: typeof BShortIdRoute
  JShortIdRoute: typeof JShortIdRoute
  JoinRoomIdRoute: typeof JoinRoomIdRoute
  RoomRoomIdRoute: typeof RoomRoomIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$roomId': {
      id: '/join/$roomId'
      path: '/join/$roomId'
      fullPath: '/join/$roomId'
      preLoaderRoute: typeof JoinRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/j/$shortId': {
      id: '/j/$shortId'
      path: '/j/$shortId'
      fullPath: '/j/$shortId'
      preLoaderRoute: typeof JShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$shortId': {
      id: '/b/$shortId'
      path: '/b/$shortId'
      fullPath: '/b/$shortId'
      preLoaderRoute: typeof BShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/results': {
      id: '/room/$roomId/results'
      path: '/results'
      fullPath: '/room/$roomId/results'
      preLoaderRoute: typeof RoomRoomIdResultsRouteImport
      parentRoute: typeof RoomRoomIdRoute
    }
    '/room/$roomId/board': {
      id: '/room/$roomId/board'
      path: '/board'
      fullPath: '/room/$roomId/board'
      preLoaderRoute: typeof RoomRoomIdBoardRouteImport
      parentRoute: typeof RoomRoomIdRoute
    }
    '/room/$roomId/wait/$userId': {
      id: '/room/$roomId/wait/$userId'
      path: '/wait/$userId'
      fullPath: '/room/$roomId/wait/$userId'
      preLoaderRoute: typeof RoomRoomIdWaitUserIdRouteImport
      parentRoute: typeof RoomRoomIdRoute
    }
    '/room/$roomId/admin/$adminKey': {
      id: '/room/$roomId/admin/$adminKey'
      path: '/admin/$adminKey'
      fullPath: '/room/$roomId/admin/$adminKey'
      preLoaderRoute: typeof RoomRoomIdAdminAdminKeyRouteImport
      parentRoute: typeof RoomRoomIdRoute
    }
    '/room/$roomId/admin/$adminKey/': {
      id: '/room/$roomId/admin/$adminKey/'
      path: '/'
      fullPath: '/room/$roomId/admin/$adminKey/'
      preLoaderRoute: typeof RoomRoomIdAdminAdminKeyIndexRouteImport
      parentRoute: typeof RoomRoomIdAdminAdminKeyRoute
    }
    '/room/$roomId/vote/$userId/$votingKey': {
      id: '/room/$roomId/vote/$userId/$votingKey'
      path: '/vote/$userId/$votingKey'
      fullPath: '/room/$roomId/vote/$userId/$votingKey'
      preLoaderRoute: typeof RoomRoomIdVoteUserIdVotingKeyRouteImport
      parentRoute: typeof RoomRoomIdRoute
    }
    '/room/$roomId/admin/$adminKey/waiting-room': {
      id: '/room/$roomId/admin/$adminKey/waiting-room'
      path: '/waiting-room'
      fullPath: '/room/$roomId/admin/$adminKey/waiting-room'
      preLoaderRoute: typeof RoomRoomIdAdminAdminKeyWaitingRoomRouteImport
      parentRoute: typeof RoomRoomIdAdminAdminKeyRoute
    }
    '/room/$roomId/admin/$adminKey/questions': {
      id: '/room/$roomId/admin/$adminKey/questions'
      path: '/questions'
      fullPath: '/room/$roomId/admin/$adminKey/questions'
      preLoaderRoute: typeof RoomRoomIdAdminAdminKeyQuestionsRouteImport
      parentRoute: typeof RoomRoomIdAdminAdminKeyRoute
    }
  }
}

interface RoomRoomIdAdminAdminKeyRouteChildren {
  RoomRoomIdAdminAdminKeyQuestionsRoute: typeof RoomRoomIdAdminAdminKeyQuestionsRoute
  RoomRoomIdAdminAdminKeyWaitingRoomRoute: typeof RoomRoomIdAdminAdminKeyWaitingRoomRoute
  RoomRoomIdAdminAdminKeyIndexRoute: typeof RoomRoomIdAdminAdminKeyIndexRoute
}

const RoomRoomIdAdminAdminKeyRouteChildren: RoomRoomIdAdminAdminKeyRouteChildren =
  {
    RoomRoomIdAdminAdminKeyQuestionsRoute:
      RoomRoomIdAdminAdminKeyQuestionsRoute,
    RoomRoomIdAdminAdminKeyWaitingRoomRoute:
      RoomRoomIdAdminAdminKeyWaitingRoomRoute,
    RoomRoomIdAdminAdminKeyIndexRoute: RoomRoomIdAdminAdminKeyIndexRoute,
  }

const RoomRoomIdAdminAdminKeyRouteWithChildren =
  RoomRoomIdAdminAdminKeyRoute._addFileChildren(
    RoomRoomIdAdminAdminKeyRouteChildren,
  )

interface RoomRoomIdRouteChildren {
  RoomRoomIdBoardRoute: typeof RoomRoomIdBoardRoute
  RoomRoomIdResultsRoute: typeof RoomRoomIdResultsRoute
  RoomRoomIdAdminAdminKeyRoute: typeof RoomRoomIdAdminAdminKeyRouteWithChildren
  RoomRoomIdWaitUserIdRoute: typeof RoomRoomIdWaitUserIdRoute
  RoomRoomIdVoteUserIdVotingKeyRoute: typeof RoomRoomIdVoteUserIdVotingKeyRoute
}

const RoomRoomIdRouteChildren: RoomRoomIdRouteChildren = {
  RoomRoomIdBoardRoute: RoomRoomIdBoardRoute,
  RoomRoomIdResultsRoute: RoomRoomIdResultsRoute,
  RoomRoomIdAdminAdminKeyRoute: RoomRoomIdAdminAdminKeyRouteWithChildren,
  RoomRoomIdWaitUserIdRoute: RoomRoomIdWaitUserIdRoute,
  RoomRoomIdVoteUserIdVotingKeyRoute: RoomRoomIdVoteUserIdVotingKeyRoute,
}

const RoomRoomIdRouteWithChildren = RoomRoomIdRoute._addFileChildren(
  RoomRoomIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BShortIdRoute: BShortIdRoute,
  JShortIdRoute: JShortIdRoute,
  JoinRoomIdRoute: JoinRoomIdRoute,
  RoomRoomIdRoute: RoomRoomIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
