name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
      id-token: write
    env:
      IMAGE: ghcr.io/progsoc/club-voting-system
      REGISTRY: ghcr.io
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: edgedb install
        run: bash <(curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com) -y

      - name: init edgedb
        run: cd apps/server && edgedb project init --non-interactive

      - name: generate edgedb schema types
        run: bun server generate

      - name: Docker Meta Release
        id: meta-release
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            # use custom value instead of git tag
            type=raw,value=latest
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta-release.outputs.tags }}
          push: true
          context: .
          labels: ${{ steps.meta-release.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:latest