name: Dev CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: init gel
        run: cd apps/server && bunx gel project init --non-interactive

      - name: generate gel schema types
        run: bun run --filter server generate

      - name: check linting
        run: bun lint

      - name: check types
        run: bun tsc -b

      - name: run tests
        run: bun test
