name: Dev CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: edgedb install
        run: bash -s "-y" < <(curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com)

      - name: install
        run: bun install

      - name: init edgedb
        run: cd src/server && edgedb project init --non-interactive

      - name: generate edgedb schema types
        run: bun server gen-edgedb

      - name: check linting
        run: bun lint

      - name: check types
        run: bun tsc
